### PR TITLE
Updates markdown to avoid right nav duplicate entries

### LINKED ISSUE #3548: ESC installation table of contents has repeated elements
File: [themes/default/content/docs/install/esc.md](https://www.pulumi.com/docs/install/esc/)

It looks like this might have something to do with the platform selection.
Screenshot 2023-10-27 at 11 25 11 AM

### PR DESCRIPTION
**Pull request by desteves**
Moves and consolidates headers up a level so that these are not nested within the language choosable shortcode. This then prevents the right nav from rendering duplicates. Headers level 1 through level 3 are updated.

The install script section was duplicated and this has been refactored into the OS-relevant sub-sections.

Fixes #3548

### CODE REVIEW

**Comment by desteves** [comment]
Direct link to the page: http://pulumi-hugo-origin-pr-3572-caf8ef3c.s3-website.us-west-2.amazonaws.com/docs/install/esc/

**Comment by cnunciato** [comment]
Hey @desteves, would you mind updating the PR title to be a bit more descriptive? Something like "Fix repeating elements in ESC on-this-page menu"?

**Comment by desteves** [comment]
> Hey @desteves, would you mind updating the PR title to be a bit more descriptive? Something like "Fix repeating elements in ESC on-this-page menu" would be good. It's helpful to have a descriptive title, especially when you're scrolling through lists of PRs and commits.

Done!

**Comment by interurban** [comment]
hey @sean1588 do you have time today for a review?

**Review by sean1588 — APPROVED** [review]
thanks for fixing @desteves!

**Comment by interurban** [comment]
Also, as we applied the page level fix, there's still a site wide (potential bug) where the right nav of the docs site sometimes contains repeated elements. Tracked here: https://github.com/pulumi/pulumi-hugo/issues/3584

**Pull request merged**
