### PR TITLE
Update the Team page

### PR DESCRIPTION
**Pull request by cnunciato**

### CODE REVIEW

**Review by jaxxstorm — APPROVED** [review]

**Comment by susanev** [comment]
@cnunciato did you want to remove Emiliza as well?

**Comment by cnunciato** [comment]
I haven't gotten a req for Emiliza yet, so will hold off on that for now.

**Comment by cnunciato** [comment]
.. a Bamboo req, that is. (I do these as part of an offboarding process.)

**Comment by susanev** [comment]
@cnunciato @leezen do yall know if we should be removing Emiliza?

**Comment by cnunciato** [comment]
PR opened just now, confirmed a bit ago.

**Pull request merged**
