### PR TITLE
Fix OpenID and tighten up some language

### PR DESCRIPTION
**Pull request by cleverguy25**
## Description

- Fix OIDC connect to OpenID Connect as the former is wrong
- Simplify some language

### CODE REVIEW

**Comment by lukehoban** [comment]
Obviously a nit at this point...

We call this "OIDC" almost everywhere in our product, docs and previous blogs.  On first mention we say "OpenID Connect (OIDC)", but then just "OIDC".    (~900 mentions of "OIDC" and ~100 of "OpenID Connect", the latter of which are mostly in the form "OpenID Connect (OIDC)" or similar)

The updates here make it technically correct, but still seemingly different than the norm in most of our other content.  I think it's still worth bringing this more inline - spell it out on first mention, then use the acronym.

**Comment by arunkumar611** [comment]
Language changes look good. I also made two minor edits. 

As Luke mentions, we'd want OIDC vs. OpenID connect to be consistent. In the first paragraph and in the first instance, we can say "OpenID Connect (OIDC)". Everywhere else we can just say OIDC.

Right now we have ~20 OIDCs and ~10 OpenID Connect in the blog.

**Comment by arunkumar611** [comment]
Do we need to update the meta.png as well? If yes, what text do we want there?

**Review by arunkumar611 — APPROVED** [review]
LGTM

**Pull request merged**
