### PR TITLE
Add meta image to Migrate Hub page

### PR DESCRIPTION
**Pull request by SaraDPH**
## Checklist:

- [ ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [ ] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [ ] I have manually confirmed that all new links work.
- [ ] I added aliases (i.e., redirects) for all filename changes.
- [ ] If making css changes, I rebuilt the bundle.

### CODE REVIEW

**Comment by SaraDPH** [comment]
@cnunciato why can't I see the image in the preview? :(

**Comment by cnunciato** [comment]
@SaraDPH The image path (in `meta_image`) and the actual location of the file don't match. I believe we're currently putting these page-specific images in `static` -- right?

**Comment by SaraDPH** [comment]
> @SaraDPH The image path (in `meta_image`) and the actual location of the file don't match. I believe we're currently putting these page-specific images in `static` -- right?
> 
> It looks like we have another image in this folder also -- we should remove that one if we're no longer using it. I'll pick this up for ya soon as I'm in.

There is another image?!

**Comment by cnunciato** [comment]
Looks good I think! 

image

**Review by cnunciato — APPROVED** [review]

**Pull request merged**
