### PR TITLE
Pulumi Service features blog post

### PR DESCRIPTION
**Pull request by cnunciato**
Any and all feedback appreciated. 🙏  Is there another feature we should call out? Is the GIF helpful, or should it just be a static image? (I think maybe static image? I don't know. I can't decide.) Is the meta image okay? Can you think of a better one? Happy to spend a little time making that better, too. 

Fixes https://github.com/pulumi/pulumi-service/issues/7786.

### CODE REVIEW

**Comment by cnunciato** [comment]
Any and all feedback appreciated. 🙏  Is the GIF helpful, or should it just be a static image? (I think maybe static image? I don't know. I can't decide.) Is the meta image okay? Can you think of a better one? Happy to spend a little time making that better, too.

**Comment by susanev** [comment]
im going to swap out my request for review with @anita-trimbur 

@anita-trimbur would love your review on this, especially related to if the information is clear and exciting to folks who are new.

**Review by anita-trimbur — APPROVED** [review]
This reads clearly to me! As a Pulumi newbie, the list items are understandable and articulate a definitive add-value. I do like the GIF; it gives me the necessary context that someone with experience using the Service may not need.

While this post generally targets people who already use the Service and may not be maximizing its potential, some extra introductory context could be useful for people with limited to no experience with the Service. As in, a line or two up front summing the high-level overview of why the Service is useful companion to the CLI may help situate newcomers. Or even a callout of "You may be familiar with x and y commonly used features..." type thing.

**Comment by cnunciato** [comment]
Thanks @anita-trimbur! That's good feedback and I agree. @chrsmith I'm happy to write a couple of introductory lines for this, unless you have something in mind already.

**Comment by cnunciato** [comment]
@anita-trimbur What do you think? Sound better?

**Comment by anita-trimbur** [comment]
@cnunciato Yes, these additions are super helpful! Looks perfect to me!

**Comment by cnunciato** [comment]
Awesome, thanks! 🍻

**Pull request merged**
