### PR TITLE
add tutorial to cloud buttons

### PR DESCRIPTION
**Pull request by susanev**
## overview

recently some folks shared that they had no idea where the cloud buttons would take them, was it to sign in, to the cloud websites, something else?

this adds the word tutorial to those buttons to make it more clear where it will send folks (though it would probably be better to be like aws + pulumi tutorial...)

let me know what yall think or if you have another idea

note: the aws logo is a special beast, ill fiddle with it later.

## before
before-docs-landing

before-get-started

## after
after-docs-landing

after-get-started

### CODE REVIEW

**Review by zchase — APPROVED** [review]
Seems reasonable to me. My only question is whether it should be labeled `Guided` instead of `Tutorial` because we refer to these things as Guides in other places.

**Comment by davidwrede** [comment]
Correct, these should be labeled as tutorials as they are step-by-step instructions centered around one scenario/goal.

**Comment by lukehoban** [comment]
I'll admit I find the word "Tutorial" in these contexts doesn't feel right.  It's really "get started with AWS".  

In the content itself we call it a "guide" - and I think that would visually look better here - though the UX of the text additions feels a bit out of place to me generally - especially on the main docs page.  That said - I don't have immediate suggestions on alternatives.  Are there other options to consider for addressing the feedback here?

**Comment by susanev** [comment]
@lukehoban im not sure that "get started with AWS" explains where we are going to send you either though...

i can spend more time here on improving the design more drastically, but I was thinking this might be good for a quick fix first. does that sound good? or do you want me to hold off until the design is improved?

**Comment by cnunciato** [comment]
I'd prefer we held off on merging this until the design is improved more holistically, yeah. Happy to hop in and help with that if you like.

**Comment by susanev** [comment]
im going to close this, but i do think we are missing a quick opportunity to make this better. i will work on redesigning our buttons for starting the tutorials.

**Pull request closed without merging**
