### PR TITLE
Add segment consent form

### PR DESCRIPTION
**Pull request by zchase**
## Description

Fixes: https://github.com/pulumi/marketing/issues/935

## Checklist:

- [ ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [ ] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [ ] I have manually confirmed that all new links work.
- [ ] I added aliases (i.e., redirects) for all filename changes.
- [ ] If making css changes, I rebuilt the bundle.

### CODE REVIEW

**Comment by SaraDPH** [comment]
@zchase, the consent form looks good. It's a bit easy to miss on a big screen - and EU people need to opt-in, by default lack of response means opt-out. Also, could you let me know if you tested the consent data flow to Google Tag Manager?

@lindsaymarolich, we need to put on our roadmap a v2.0. This version complies with CNIL, CCPA, LGPD, SB-220, and PDPA. Yet, it's in a grey area for GDPR and lacks some ICO best practices.

**Comment by zchase** [comment]
@SaraDPH There isn't a way to prompt on a 3rd visit because we have no way of tracking them until they opt in. The banner will show on the screen until they either opt-in or opt-out.

We will need to defer to @anita-trimbur on how to make the banner more visible.

**Comment by SaraDPH** [comment]
@zchase doesn't Segment collect that data? To some extent, our "owned" cookies can be considered Essential.

It shouldn't be a blocker for banner implementation, but ideally, it should have that as a next step behavior trigger, three visits if opt-out or not yet opt-in, show banner.

**Comment by zchase** [comment]
@SaraDPH Segment won't load until a user opts-in so we won't have any data until the user takes an action. We do collect user preferences in local storage so maybe we _could_ key off that since we set defaults. I can look into it adding some date field we can key off of.

**Review by shughes26 — APPROVED** [review]

**Review by sean1588 — APPROVED** [review]

**Pull request merged**
