### PR TITLE
Sarah/pulumiup event day

### PR DESCRIPTION
**Pull request by shughes26**
## Description
PulumiUP landing page updates for after the event (https://github.com/pulumi/pulumi-hugo/issues/3014)

## Checklist:

- [x] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [x] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [x] I have manually confirmed that all new links work.
- [x] I added aliases (i.e., redirects) for all filename changes.
- [x] If making css changes, I rebuilt the bundle.

### CODE REVIEW

**Comment by susanev** [comment]
up to yall, but the size increase on this ad, really changes the vibe in the docs
docs-ad

**Review by zchase — APPROVED** [review]

**Comment by shughes26** [comment]
Strange that the image is visibly larger in the file diff but dimensions are smaller. 

image

**Comment by lindsaymarolich** [comment]
Interesting, I didn't mean for it to be any larger. I can resize this, if helpful, but since it looks like the dimensions are already smaller not sure that it would work?

**Comment by shughes26** [comment]
@lindsaymarolich let's leave the image as-is, I can enforce the size of the ad programmatically. Update incoming!

**Pull request merged**
