### PR TITLE
repeat case studies in the learn menu

### LINKED ISSUE #779: add case studies to learn menu
## overview
to help make our case studies easier to find, lets add a `Case Studies` nav item to the learn menu between the blog and resources items. this item should send folks to `https://www.pulumi.com/case-studies/`. pls note there are no changes to the cloud eng menu in this issue, and the case studies item should remain there.

this was a collaboration between @susanev and @gthuang and approved by jay

## design details
- [x] add a `Case Stuides` item between blog and resources items in the learn menu that sends folks to `/case-studies`
- [x] no changes to the case studies item in the cloud eng menu
- [x] no need to update in the mobile nav, as everything is exposed and case studies is already included

### PR DESCRIPTION
**Pull request by susanev**
fixes #779

### CODE REVIEW

**Comment by susanev** [comment]
@zchase i forgot to check in with you about this, are there any SEO concerns to repeating a link in the top navigation?

**Review by cnunciato — APPROVED** [review]
This seems fine, but why _shouldn't_ we add it to the Learn menu on mobile as well, so the two menus contain the same items?

**Comment by susanev** [comment]
@cnunciato because the mobile menu displays as one entire unit, its not individual menus. and the case studies already shows up there. at least that was my thinking. do you feel strongly? if so i can add it.

**Comment by cnunciato** [comment]
Nah, I don't feel strongly or anything, and I see what you mean. 👍

**Review by gthuang — APPROVED** [review]

**Pull request merged**
