### PR TITLE
Add link to public roadmap blog on /product/

### PR DESCRIPTION
**Pull request by gthuang**
Surface the public roadmap in the "open source" section of our product page

### CODE REVIEW

**Comment by gthuang** [comment]
@cnunciato I'm having trouble getting the linking to work in here.

**Comment by cnunciato** [comment]
@gthuang Ah, I see -- we just need to make a little tweak to the template to honor that Markdown linking syntax. Mind if I push a commit onto your branch?

**Comment by gthuang** [comment]
@cnunciato yep please do

**Comment by susanev** [comment]
im glad we are linking to this here, should we possibly consider linking to it in the footer as well?

**Comment by gthuang** [comment]
@susanev where exactly do you suggest adding it?

**Comment by susanev** [comment]
in the footer.

two options that i think would work well...

- third column, between contact us and support
- first column at the bottom

**Comment by gthuang** [comment]
@susanev I think at the bottom of the first column makes a lot of sense to me.

**Comment by cnunciato** [comment]
@gthuang Ok, should be all set. (And sorry for the spacing noise; my editor applied it.)

**Comment by gthuang** [comment]
thanks @cnunciato !

**Comment by gthuang** [comment]
@cnunciato so the link works but the text looks just like regular text so you can't tell there's a link there. do you know how to make it so that it's underlined (just like how it is in the rest of the page)?

**Comment by cnunciato** [comment]
Ah, I see what you mean -- it's blue, which is the default. I'll take a peek at how the others on the page are defined and see if I can emulate that.

**Comment by cnunciato** [comment]
Ok, just pushed up a change that should do the trick. Let me know what you think!

**Review by cnunciato — APPROVED** [review]
Adding an approval here so this can be merged whenever you like @gthuang.

**Comment by gthuang** [comment]
@cnunciato thanks looks great!

**Pull request merged**
