### PR TITLE
get started enhancements

### LINKED ISSUE #1715: make get-started guides a single page
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Reduce the get-started guides from 9 pages to a single page.

### LINKED ISSUE #1716: clarify get-started guide buttons
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
the AWS, GCP, Azure, Kubernetes buttons are sligthly confusing to new users and could better indicate their intent. In usability studies, some users seemed unaware that the buttons were buttons or clickable.
2022-07-07-141910_1919x1025_scrot

### LINKED ISSUE #1717: get-started enhancements

### PR DESCRIPTION
**Pull request by dixler**
changes:
- [x] modified the get started landing page.
- condensed the get started content to a single page.
  - [x] AWS
  - [x] GCP
  - [x] Azure
  - [x] K8S
 - [x] make sure to add all aliases and redirects to pages to this document.
 - [x] clean up section transitions.

Fixes #1715 
Fixes #1716

### CODE REVIEW

**Comment by dixler** [comment]
aliases: [
  "/docs/quickstart/aws/",
  "/docs/quickstart/aws/begin/",
  "/docs/quickstart/aws/install-pulumi/",
  "/docs/quickstart/aws/install-language-runtime/",
  "/docs/quickstart/aws/configure/",
  "/docs/get-started/aws/install-pulumi/",
  "/docs/get-started/aws/install-language-runtime/",
  "/docs/get-started/aws/configure/",
  "/docs/get-started/aws/begin",
  "/docs/get-started/aws/create-project",
  "/docs/get-started/aws/deploy-changes",
  "/docs/get-started/aws/deploy-stack",
  "/docs/get-started/aws/destroy-stack",
  "/docs/get-started/aws/modify-program",
  "/docs/get-started/aws/next-steps",
  "/docs/get-started/aws/review-project",
  "/docs/quickstart/aws/create-project/",
  "/docs/quickstart/aws/review-project/",
  "/docs/quickstart/aws/deploy-stack/",
  "/docs/quickstart/aws/modify-program/",
  "/docs/quickstart/aws/deploy-changes/",
  "/docs/quickstart/aws/destroy-stack/",
  "/docs/quickstart/aws/next-steps/"
]

**Comment by dixler** [comment]
@lukehoban @susanev I have merged the get-started pages into their own pages and added some changes around the get-started landing page to convey that the video is a demo of the guides and that the buttons are clickable.

Assuming we make sure CI/CD can deploy these changes, does the formatting look better?

**Comment by dixler** [comment]
some notes:
- our docs are very heavy on prose so I think the feel of this get-started guide may be a little more intimidating than having a bunch of small pages. I think cutting down on prose first to make it smaller may be better than deploying it as is.

**Comment by susanev** [comment]
@dixler im up for trying this! thx for opening the pr. my only hesitation is the next steps section seems quite out of place now that its not its own page, i wonder if we should possibly rethink that section. no need to block, though if we want to try this out.

how are we going to watch the data to know if this has made a positive impact?

ps i have lots of time tomorrow (only 1 meeting) if ya want to help with the broken parts.

**Pull request closed without merging**
