### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by SaraDPH**
Add meta_image Azure with Java

### CODE REVIEW

**Comment by SaraDPH** [comment]
I didn't know how to add https://github.com/pulumi/pulumi-hugo/pull/2114 together

**Comment by sean1588** [comment]
> I didn't know how to add https://github.com/pulumi/pulumi-hugo/pull/2114 together

no worries, @SaraDPH . I'll group them together in this PR for you. Also, the folder where you added the image to, it won't get picked up from that location for some reason. It needs to be added to `themes/default/static/images/` in order for it to work. I'll get it fixed up for you and bundled into this PR. 
 
On a side note, I am in the process building a tool to help automate a lot of this where you can just edit and create the workshops and it will auto open PRs for you with the changes. Here is the link if you want a preview of it. https://press.corptron9000.pulumi.com/

**Comment by sean1588** [comment]
ok I closed the other PR and added the image here and also put it in the "themes/default/static/images/" folder.

**Review by sean1588 — APPROVED** [review]

**Review by susanev — APPROVED** [review]

**Comment by susanev** [comment]
@SaraDPH is this good to merge?

**Pull request merged**
