### PR TITLE
Add a two boxed Pulumi logos for Github

### PR DESCRIPTION
**Pull request by cobraz**
This pull request adds two new types of Pulumi logos, meant to use on public Github repositories.

See a much more in-depth description in pulumi/pulumi#6865.

### CODE REVIEW

**Comment by susanev** [comment]
@cobraz would you mind adding a few details about what you are fixing here?

**Comment by cobraz** [comment]
Or, sorry, @susanev! I forgot to add a description here, see the updated one now!

**Comment by susanev** [comment]
ah i see @cobraz lets got with the no-shadow version, wish we could use our logo-on-dark for these, but understand why we cant.

thanks for fixing this!!

**Comment by cobraz** [comment]
> ah i see @cobraz lets go with the no-shadow version, wish we could use our logo-on-dark for these, but understand why we cant.
> 
> thanks for fixing this!!

Yeah, it's sad. I'll be sure to pay attention to see if something comes up that can make it possible, like the [feature request](https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/53) for a theme context. We could use media queries and `prefers-color-scheme`, but it doesn't work good enough, since users can activate dark mode on Github, but keep browser/OS in light mode; stuck with the same issue as right now.

I'll update the PR to remove the shadow version :)

**Comment by cobraz** [comment]
Done :)

**Review by susanev — APPROVED** [review]

**Pull request merged**
