### PR TITLE
Convert to comprehensive pulumi/devcontainer git submodule

### PR DESCRIPTION
**Pull request by usrbinkat**
## Description

PR to import the github.com/pulumi/devcontainer repository as a git submodule.

This container includes:

- hugo
- pulumi cli
- pulumictl cli
- pulumi esc cli
- golang
- python
- dotnet
- nodejs
- yarn
- and a few other nice to haves

## Testing

To try it yourself:

1. use click menu to open PR in github codespaces
2. execute `make` command in vscode terminal
3. open site built 'locally' in a new tab when prompted

## Motivation

At this time, basic activities, including writing IaC, submitting blog posts and tutorials, and developing new providers includes many prerequisite steps

## Checklist:

- [ ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [ ] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [ ] I have manually confirmed that all new links work.
- [ ] I added aliases (i.e., redirects) for all filename changes.
- [ ] If making css changes, I rebuilt the bundle.

### CODE REVIEW

**Comment by desteves** [comment]
For the testing steps, this is what I did:

go to https://github.com/pulumi/pulumi-hugo/tree/feat/usrbinkat/devcontainer -> "<>" -> "Codespaces +" -> Click the "+" which reads "create a codespace on feat/usrbinkat/devcontainer"
// wait about 10 minutes ...
execute `make` command in vscode terminal 
click http://localhost:1313/  which the forwards it to a working endpoint (https://silver-space-barnacle-4g995495r52q4vw-1313.app.github.dev/) in my case


LGTM!

**Comment by desteves** [comment]
I think there's just some minor lint things to address so that all the checks pass.

**Comment by cnunciato** [comment]
When I try to activate this locally (using the VS Code extension), it fails on this: 

image

**Review by cnunciato — APPROVED** [review]
Nice work! ⭐ The CodeSpaces workflow is nice, and seems to work a bit better than the local dev-container workflow, but the issues with that (Git SSH, Arm support) exist with the current dev container also, so I'm good to roll forward with this and keep iterating. Thanks!

**Pull request merged**
