### PR TITLE
Remove -b content from getting-started guides

### PR DESCRIPTION
**Pull request by cnunciato**
Now that the experiment these pages were built for is complete, we can safely remove them.

### CODE REVIEW

**Comment by zchase** [comment]
@cnunciato Sounds like @interurban has some ideas around experimentation with Pulumi AI in the Getting Started guide, some might be a good idea to keep these around for a bit.

**Review by desteves — APPROVED** [review]

**Comment by desteves** [comment]
Given @zchase comment to keep this around a while longer. I'm labeling this as `do-not-merge`. Thoughts on closing this as well? @cnunciato

**Comment by zchase** [comment]
@desteves @cnunciato I sync'd with @interurban on this and we go ahead and remove this. We won't be using this for adding AI to the guide.

**Comment by desteves** [comment]
Will be removing -b pages.

**Pull request merged**
