### PR TITLE
Sarah/4ir

### PR DESCRIPTION
**Pull request by shughes26**
## Description
Case Study for 4IR added per https://github.com/pulumi/marketing/issues/841

Because the case study template is used for all case studies, we can add the purple block and CTA changes to all case studies as a separate issue.

## Checklist:

- [x] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [x] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [x] I have manually confirmed that all new links work.
- [x] I added aliases (i.e., redirects) for all filename changes.
- [x] If making css changes, I rebuilt the bundle.

### CODE REVIEW

**Comment by lindsaymarolich** [comment]
@aaronkao Eli mentioned you were going to review this as well, have you had a chance to? She would like us to push live today.

**Comment by elistaykova** [comment]
@lindsaymarolich - so @aaronkao already reviewed, and I gave it one final review/edit last night. The copy for Shoes is updated and ready to go here. Please have her upload that final copy: https://docs.google.com/document/d/1W7iDIXPfgB6LgmJMHA1kPs1aa07eNvEUaP43gAqOOxg/edit#heading=h.7w2g9kitqrgq

**Comment by ericrudder** [comment]
please, don't do this.

the copy edit definitely still has some issues with grammar, capitalization
and passive voice.

i will take a look later in the morning, however i do want to give a go
here.

**Comment by lindsaymarolich** [comment]
@ericrudder once you've signed off please let us know and we can get any updates staged

**Comment by ericrudder** [comment]
alright, i gave it a pass. it's as good as it's going to get.

thanks

**Comment by lindsaymarolich** [comment]
@shughes26 this is ready to go -- please note that the copy has been updated

**Review by lindsaymarolich — APPROVED** [review]

**Pull request merged**
