### PR TITLE
Add new tutorials

### PR DESCRIPTION
**Pull request by toriancrane**
## Description

This PR is adding two new tutorials to the site. The tutorials have been added under a new folder called `tutorials` in preparation for the new tutorials experience. Until the new experience is launched, they will temporarily live in the `Using Pulumi` section of the site.

This PR also includes a new shortcode for injecting the contents of a separate code file into the main index file.

Will resolve [this issue](https://github.com/pulumi/docs/issues/10207).

## Relevant URL Paths

- Using Pulumi hub page: `/docs/using-pulumi/`
- Defining and Provisioning Resources tutorial: `/docs/tutorials/define-and-provision-resources/`
- Stack References and Outputs tutorial: `/docs/tutorials/stack-outputs-and-references/`

### CODE REVIEW

**Comment by desteves** [comment]
- Can we add a little info note that if one gets the error:
- “creating EC2 Instance: InvalidAMIID.NotFound: The image id '[ami-09538990a0c4fe9be]' does not exist” is because the AMI doesn’t exist and they need to update it to match the region’s available AMIs. For us-west-2, use `ami-06e2a005a056f76d7`

**Comment by toriancrane** [comment]
> Defining and Provisioning Resources tutorial:
> 
> * Can we add a little info note that if one gets the error:
>   `“creating EC2 Instance: InvalidAMIID.NotFound: The image id '[ami-09538990a0c4fe9be]' does not exist”` is because the AMI doesn’t exist and they need to update it to match the region’s available AMIs. For us-west-2, use `ami-06e2a005a056f76d7`

Great catch! Added.

**Comment by desteves** [comment]
In the preview / files changed for Defining and Provisioning Resources tutorial, I noticed the typescript files end in `.txt`. Do we want to update them to `.ts`?

**Comment by desteves** [comment]
Add a note that the default aws profile will be used? I think it's fairly obvious but I could use a remainder now to help me when walking through the steps.

http://pulumi-hugo-origin-pr-3574-343c1338.s3-website.us-west-2.amazonaws.com/docs/tutorials/stack-outputs-and-references/#access-outputs-via-the-cli

**Comment by desteves** [comment]
I followed the python code examples, all good.

**Comment by toriancrane** [comment]
> In the preview / files changed for Defining and Provisioning Resources tutorial, I noticed the typescript files end in `.txt`. Do we want to update them to `.ts`?

Updated.

**Comment by toriancrane** [comment]
> Add a note that the default aws profile will be used? I think it's fairly obvious but I could use a remainder now to help me when walking through the steps.
> 
> http://pulumi-hugo-origin-pr-3574-343c1338.s3-website.us-west-2.amazonaws.com/docs/tutorials/stack-outputs-and-references/#access-outputs-via-the-cli

Added.

**Comment by toriancrane** [comment]
> http://pulumi-hugo-origin-pr-3574-343c1338.s3-website.us-west-2.amazonaws.com/docs/tutorials/stack-outputs-and-references/#reference-the-name-of-the-lambda-function we can add a note to run `pulumi stack ls` ?

Unless I am misunderstanding, there should be no reason for users to have to do this since they are creating a new project/stack in a new directory to work from.

**Comment by toriancrane** [comment]
> In the preview / files changed for Defining and Provisioning Resources tutorial, I noticed the typescript files end in `.txt`. Do we want to update them to `.ts`?

I [now remember why](https://github.com/pulumi/pulumi-hugo/actions/runs/6742824500/job/18329600565?pr=3574) I changed the files to .txt ending lol there are incomplete code examples (on purpose) and the build tests dont like that. Changing it back for now.

**Comment by desteves** [comment]
> > http://pulumi-hugo-origin-pr-3574-343c1338.s3-website.us-west-2.amazonaws.com/docs/tutorials/stack-outputs-and-references/#reference-the-name-of-the-lambda-function we can add a note to run `pulumi stack ls` ?
> 
> Unless I am misunderstanding, there should be no reason for users to have to do this since they are creating a new project/stack in a new directory to work from.

Gotcha, I only used command to help me figure out the fully qualified name

**Review by desteves — APPROVED** [review]
lgtm

**Pull request merged**
