### PR TITLE
Final CED updates

### PR DESCRIPTION
**Pull request by shughes26**
https://github.com/pulumi/marketing/issues/661

### CODE REVIEW

**Comment by SaraDPH** [comment]
@shughes26 can you add more space between sections? 

1. Without the whitespace, the page feels very compressed. It's often better to have more whitespace than less. Also, some alignments need to be fixed. Please see the example image below for alignments.

Reference on whitespace: https://www.seguetech.com/whitespace-web-design/

image

2. Needs to be updated to show the video: https://www.pulumi.com/resources/simpler-pulumi-package-authoring/

3. Can the video-event template be updated to have the name of the event before the video? @zchase do you own these? 
Example: 
image
http://pulumi-hugo-origin-pr-2356-82ffda6a.s3-website.us-west-2.amazonaws.com/resources/building-a-global-data-platform-at-scale/

**Comment by shughes26** [comment]
@SaraDPH just did a new push to add some extra padding around sections, youtube link added for simpler pulumi package authoring, and added "Cloud Engineering Days 2022" to the title for the replay page template

**Review by zchase — APPROVED** [review]

**Comment by SaraDPH** [comment]
@shughes26 I saw the Zack approved, and it was merged. Why isn't live then?

**Comment by shughes26** [comment]
@SaraDPH looks like there are some issues with hugo deployments

**Pull request merged**
