### PR TITLE
Add hand raise section to the majority of pages

### PR DESCRIPTION
**Pull request by zchase**
This PR adds the Hand Raise section to the majority of pages on the website. I added it to docs/blog pages as well as those are high traffic areas.

### CODE REVIEW

**Comment by cnunciato** [comment]
@zchase Still want to keep this open?

**Comment by zchase** [comment]
@cnunciato Yeah I just rebased the branch but it would be nice to get his merged in eventually.

**Comment by cnunciato** [comment]
@zchase Ok cool, sounds good! I think we'll just need to move the components and CSS to the theme repo, though, and then once that's in, we should be able to get this merged. Sorry for the extra step -- if you want, I'd be happy to move this stuff over for ya, since I'm to blame for it. 😇

**Comment by susanev** [comment]
closing for now. we will reopen when we revisit this work.

**Pull request closed without merging**
