### PR TITLE
update sponsors for pulumiUP

### PR DESCRIPTION
**Pull request by shughes26**
## Description
sponsors updated with links

## Checklist:

- [x] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [x] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [x] I have manually confirmed that all new links work.
- [x] I added aliases (i.e., redirects) for all filename changes.
- [x] If making css changes, I rebuilt the bundle.

### CODE REVIEW

**Comment by SaraDPH** [comment]
@shughes26 can you move Port down so CircleCI isn't by itself?
image

**Comment by shughes26** [comment]
> @shughes26 can you move Port down so CircleCI isn't by itself? image

@SaraDPH It's the wrapping that causes this. I can decrease the section's width percentage to make the whole section narrower, but I can't force the list to wrap at a certain logo. Should I do that?

**Comment by SaraDPH** [comment]
> > @shughes26 can you move Port down so CircleCI isn't by itself? image
> 
> @SaraDPH It's the wrapping that causes this. I can decrease the section's width percentage to make the whole section narrower, but I can't force the list to wrap at a certain logo. Should I do that?

I suppose?! Whatever it was done to keep the clouds by themselves, to do with the rest but probably not so "tight." Did that make sense? Clearly, I don't know how it is actually done. Hah.

**Comment by shughes26** [comment]
@SaraDPH I found a quick way to force a 3-4-3 lineup, new preview should have it

**Review by SaraDPH — APPROVED** [review]
It looks great. Thanks

**Pull request merged**
