### PR TITLE
Adjust docs & blog layout for tablets

### PR DESCRIPTION
**Pull request by cnunciato**
This uses the mobile layout up to iPad width, which makes browsing the docs and blog a lot nicer on a tablet. (This used to be fine before the redesign, so I suspect between the redesign itself and the post-redesign upgrade to Tailwind 2, something must've shifted.)

Before: 

image

After:

image

### CODE REVIEW

**Comment by susanev** [comment]
i dont think we should use the hamburger icon again, since we already have that for the top nav. let me think about this a bit and figure out if another icon can work here.

**Comment by cnunciato** [comment]
Ok. This is the same one we've been using for this for a few years now -- can we merge this and come back to fix the icon in a follow-up to unbreak? (Unless you think you'll have something soon.)

**Comment by susanev** [comment]
if i dont come up with something today you can merge

**Comment by cnunciato** [comment]
One of y'all mind giving this a 👍 so I can merge, assuming no other issues?

**Comment by susanev** [comment]
oh i was hoping to switch to a label instead of an icon, its still on my list for today to add the details. do you need to merge it now, I suppose I can open a separate issue if so.

**Comment by cnunciato** [comment]
That'd be fine to do as a quick follow-up, yeah, considering this PR doesn't change anything other than breakpoints.

**Review by susanev — APPROVED** [review]

**Comment by cnunciato** [comment]
@susanev thank you!

**Pull request merged**
