### PR TITLE
Third nav implementation on resources + brand resources pages

### PR DESCRIPTION
**Pull request by kimberleyamackenzie**
This PR is for implementing a new third nav design on the brand resources + resources pages.  The bulk of the code changes are in theme: https://github.com/pulumi/theme/pull/83, where I implemented a new reusable component for this nav functionality.  I used that component for the brand resources page, but had to implement the resources page separately because of how we use the nav as a filter there - but future implementations of a tertiary nav in this style should be easy with the new component.

### Changes in this PR:
- [ ] New third nav 🎉 
- [ ] On brand resources page, content is only shown for the active tab (this was already the resources page behavior)
- [ ] Scrollability on the nav in the brand resources page.  This is implemented with arrows on screens above 1024px, below that we remove those arrows (but maintain scrollability) because of how the arrow behavior gets kind of funky and hard to manage.
- [ ] Small adjustment to mobile display of brand resources page, with stacking buttons instead of side by side

Screen Shot 2022-03-10 at 10 23 00 AM
Screen Shot 2022-03-10 at 10 23 10 AM
Screen Shot 2022-03-10 at 10 25 30 AM
Screen Shot 2022-03-10 at 10 26 28 AM

### Links
Designs: https://www.figma.com/file/VRCp6m8TyfCN4tZugJiyh7/Third-Nav-Design?node-id=3%3A273 & https://www.figma.com/proto/VRCp6m8TyfCN4tZugJiyh7/Third-Nav-Design?node-id=3%3A1161&scaling=scale-down-width&page-id=3%3A273&starting-point-node-id=3%3A1161

Ticket: https://github.com/pulumi/pulumi-hugo/issues/73

### To-do
- [ ] This PR is connected to my theme PR.  Once these are ready to go in, I will update this to use the release branch of theme.

### CODE REVIEW

**Comment by cnunciato** [comment]
I'll need a bit of time to get through this PR and the accompanying theme changes (I've started, should be able to finish today), but a couple of things I've noticed:

* On the brand page, the tabs don't get pointer cursors (though they seem to on other pages)?
* Things seems to be getting clipped (hiding nav items) even when there's more than enough horizontal space to show all of them):
    image

    We should really only clip/hide these nav items when we absolutely have to, IMO, since they're the main way of understanding and using this page. Should be possible to continue doing this, at least on desktop (as we do today).

**Comment by jonelleb** [comment]
@kimberleyamackenzie I think everything looks great! Thanks for the fast turn around! 
@cnunciato, Kimberley and I just spoke and really the issue with widening the nav space happens when there are scroll icons, so she's going to remove the scroll and show all six links and we'll only use the scroll icons when necessary (on pages that have over 6 links and/or long text). Thanks!

**Review by cnunciato — COMMENTED** [review]
Ok, I think I have some high-level questions about this:

* We seem to be using `pulumi-tertiary-nav` to show and hide content, whereas today, we don't use the existing nav (the one this new nav is presumably intended to replace) to show and hide content -- we just show all content, and use the nav (which used to be sticky) to anchor to individual sections. I do think we should retain the behavior we have today, though; I don't think we should change things up to show only one section at a time. (Indeed, the first thing I did when I looked at the brand page was scroll down and wonder what'd happened to the colors.)

* The tertiary-nav component seems like it _wants_ to be a general-purpose tab-set component, which in principle I like (separate from using it as a nav replacement), but the component isn't quite written to work that way yet -- which makes me wonder what we're gaining by _having_ the component, given that it essentially relies on structured/page-specific frontmatter and is also aware of the global context (e.g., it uses jQuery). I'd kind of expect us to go either way -- either use jQuery alone (which would IMO be totally fine considering we're just toggling CSS classes at this point) or go full-on component and have _all_ of the display logic happen inside the component, exposing more of a slot-based API.

Just some initial thoughts; happy to sync up over Zoom as well if it'd help keep things moving.

**Comment by jonelleb** [comment]
I did some research (one of them being on the Nielsen Norman Group site) and  found that in-page links are often confusing for users - normally links lead to another page, when that expectation isn’t met, users can get disoriented.
Also, users usually skim content so I think it would be better to separate the content into shorter, more manageable pieces instead having a large amount of lengthly content on one page. And a page with brief sections doesn’t require as much scrolling effort. Those were my reasons behind the new nav behavior on the Brand Resources page, but if keeping links as in-page/anchor type links is preferred that's fine.

**Comment by susanev** [comment]
Yes, this was an intentional design choice. We present these as navigation but they are not navigation, they are anchor links. This is quite confusing and unexpected for users. There is also no known need for users to consume the colors and the logos at the exact same time, so there is not a need to present them on the page at the same time.

**Comment by cnunciato** [comment]
Ok thanks y'all, I appreciate the discussion. I think I maybe got the wrong impression on intended scope here. 

If these design changes are meant to apply only to the Resources and Brand pages, then that's all good. I think because the Brand page (today) uses the same anchor-based subnavigation as our whitepaper and case-studies pages, and the issue linked from this PR mentions changing those pages as well, I was assuming the design changes in this PR would be applied to those pages also. It sounds like that may not be the case -- and if so, awesome, this all seems fine design-wise.

**Comment by cnunciato** [comment]
Ok yeah -- now I see now that I missed everything from this comment down: https://github.com/pulumi/theme/issues/80#issuecomment-1063400956

Apologies for that!

**Comment by kimberleyamackenzie** [comment]
@cnunciato I incorporated the majority of your feedback into the theme PR, and re-triggered a build here.  In addition to some of the smaller tweaks, I wrapped the intersection observer in a conditional to prevent being called on pages where the element doesn't exist and updated the resources page to show all 6 links at larger screen sizes when that's possible (see screenshot below).

> The tertiary-nav component seems like it wants to be a general-purpose tab-set component, which in principle I like (separate from using it as a nav replacement), but the component isn't quite written to work that way yet -- which makes me wonder what we're gaining by having the component, given that it essentially relies on structured/page-specific frontmatter and is also aware of the global context (e.g., it uses jQuery). I'd kind of expect us to go one way or the other, though -- either use jQuery alone (which IMO would be totally fine considering we're just toggling CSS classes at this point) or go full-on component and have all of the display logic happen inside the component, exposing more of a slot-based API of some sort.

I think one of the big benefits of having the component is it helps us avoid having to duplicate a lot of complicated css/js anywhere else we want to use this.  I agree that a slot-based API would be a little more generalizable, but that feels like a bit heavier of a lift than we need at the moment - I was just trying to solve the problem of being able to add this third nav to additional pages in a few lines, as opposed to recreating classes + styles each time we want to do so.  If you're open to it, I'd like to leave the component as-is for now, and revisit going more full-on component if and when we see that we're using this more broadly.

**Review by cnunciato — APPROVED** [review]
@kimberleyamackenzie Thanks for that jQuery tweak on the component; that definitely helps. Ok! Sounds like we're all on the same page with regard to the tradeoffs here, so I'm okay rolling forward with this. And thanks again for the discussion. 🚀

**Review by zchase — APPROVED** [review]
LGTM to but we should consider filing a follow-up issue to make `pulumi-tertiary-nav` more multi-purpose and a bit clearer on how to code it up. My personal preference is to have something like:

```
<pulumi-tertiary-nav>
    <section id="section-1">
    </section>

    // More children
</pulumi-tertiary-nav>
```

That way it is a bit clearer in the HTML what is actually being managed by the component. This sort of approach should also work for `/resources` as we can just create the static sections in HTML rather than do the JS sorting. That requires somewhat of a refactor for the `/resources` HTML code but something I'd be happy to tackle if there is a general-use component.

**Review by jonelleb — APPROVED** [review]
Everything looks great and is approved by me. Thanks for updating!

**Comment by jonelleb** [comment]
@kimberleyamackenzie - Looks great!

**Pull request merged**
