### PR TITLE
update note styles

### PR DESCRIPTION
**Pull request by susanev**
## Description
fixes: https://github.com/pulumi/docs/issues/8975

we should not merge this until the docs nav reorg lands

Screenshot 2023-05-18 at 10 05 21 AM
Screenshot 2023-05-18 at 10 04 44 AM
Screenshot 2023-05-18 at 10 04 24 AM
Screenshot 2023-05-18 at 10 04 19 AM

## Checklist:

- [x] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [x] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [x] I have manually confirmed that all new links work.
- [x] I added aliases (i.e., redirects) for all filename changes.
- [x] If making css changes, I rebuilt the bundle.

### CODE REVIEW

**Comment by anita-trimbur** [comment]
responded to your questions in figma! let me know if that makes sense or if i missed anything

**Comment by anita-trimbur** [comment]
from figma
* [ ] re: switching from orange to pink; i don't mind switching to pink, the orange was intended to align with our warning color in the service. i'm inclined to to believe that orange/yellow are often used in warning contexts whereas red/pink are used in error contexts
* [ ] are we using this component for deprecation messages? if yes, i can make another style - may want to consider the pink here instead

**Comment by susanev** [comment]
@anita-trimbur lets write up a separate issue for deprecation note styles

**Comment by anita-trimbur** [comment]
i think the background color for the code styles are appearing slightly darker here than in figma - or do you think this is the right level of contrast?

**Review by sean1588 — APPROVED** [review]
approving the code change here. i'll leave the styling chages part to anita

**Pull request merged**
