### PR TITLE
Add Robbie McKinstry to the team page.

### PR DESCRIPTION
**Pull request by RobbieMcKinstry**
🎉 

Not sure who to add as a reviewer on this. 🤷🏻‍♂️ Adding Kimberley since the commit logs indicate to me you're the closest person to a code owner I can find for this repo! Apologies for the noise.

### CODE REVIEW

**Review by kimberleyamackenzie — APPROVED** [review]
lgtm! :shipit:

**Review by susanev — COMMENTED** [review]
@RobbieMcKinstry do you mind reducing ur image size? the max pixel dimensions it will ever be is 192 x 192, and urs is 3007 x 3007 and 3.6 mb

**Comment by RobbieMcKinstry** [comment]
Done! 54kb feels a lot better! Ironically this t-shirt is the company shirt for my last employer! @anita-trimbur took this photo when she did the company headshots. Sorry to let you down again Susan 😭 😂

**Comment by RobbieMcKinstry** [comment]
Done! 54kb feels a lot better! Ironically this t-shirt is the company shirt for my last employer! @anita-trimbur took this photo when she did the company headshots. Sorry to let you down again Susan 😭 😂

**Pull request merged**
