### PR TITLE
Nav & search updates

### PR DESCRIPTION
**Pull request by kimberleyamackenzie**
This PR is the set of changes in pulumi-hugo related to a larger set of changes across Registry, Hugo, and Theme to 
1) bring the Registry search and hugo docs search more in line with each other ([#835](https://github.com/pulumi/registry/issues/835))
2) make some styling changes to search (including some follow-up items frrom the initial Registry launch) ([#178](https://github.com/pulumi/registry/issues/178), [#167,](https://github.com/pulumi/registry/issues/167) and [#835](https://github.com/pulumi/registry/issues/835))
3) Fix some quirks of how the dropdown nav interacts with the sticky nav ([#107](https://github.com/pulumi/theme/issues/107))

### Related tickets + PRs
https://github.com/pulumi/registry/issues/178
https://github.com/pulumi/registry/issues/167
https://github.com/pulumi/registry/issues/835
https://github.com/pulumi/theme/issues/107
https://github.com/pulumi/user-experience/issues/32

Registry PR: https://github.com/pulumi/registry/pull/936/
Theme PR: https://github.com/pulumi/theme/pull/138
Hugo PR: https://github.com/pulumi/pulumi-hugo/pull/1513/

### Testing
Granular specifics are noted in the linked issues, but overall, when visiting the preview links, you should see that Hugo docs search + Registry search look and behave the same.  The dropdown Pulumi menu should disappear in either preview when you click out, or start scrolling.  These changes are intended to work for all breakpoints.  Please flag if there's anything weird, cut off, misaligned between the two, or otherwise unexpected!

http://pulumi-hugo-origin-pr-1513-a99f4aa4.s3-website.us-west-2.amazonaws.com/docs/
http://registry-origin-pr-936-1e7f2bec.s3-website.us-west-2.amazonaws.com/registry/

#### Currently in prod
Screen Shot 2022-05-16 at 1 25 24 PM
Screen Shot 2022-05-16 at 1 25 44 PM
Screen Shot 2022-05-16 at 1 25 51 PM

#### With this change
Screen Shot 2022-05-16 at 1 24 44 PM
Screen Shot 2022-05-16 at 1 24 56 PM
Screen Shot 2022-05-16 at 1 25 06 PM

### CODE REVIEW

**Comment by kimberleyamackenzie** [comment]
Adding DO NOT MERGE label - this PR should not merge until all 3 related PRs are ready to merge.

**Comment by susanev** [comment]
@kimberleyamackenzie something went weird here...
registry-weirdness

**Comment by susanev** [comment]
@kimberleyamackenzie something went weird in registry...
registry-weird

**Comment by susanev** [comment]
@kimberleyamackenzie unsure if im using ur preview links wrong, but from the registry link im getting...
registry-search

**Comment by kimberleyamackenzie** [comment]
@susanev okay, the registry preview link should be all fixed up - i updated all the PR descriptions with the new link: http://registry-origin-pr-936-1e7f2bec.s3-website.us-west-2.amazonaws.com/registry/

**Review by susanev — APPROVED** [review]

**Comment by susanev** [comment]
go for it, thx!

**Review by sean1588 — APPROVED** [review]

**Pull request merged**
