### PR TITLE
fix buttons on home on smaller screens

### PR DESCRIPTION
**Pull request by susanev**
## before
before

## after
after

### CODE REVIEW

**Comment by susanev** [comment]
@zchase @kimberleyamackenzie this works locally for me but that preview link, it goes to column but then back to row for super small screens so imma prolly need some of yalls help tomorrow if possible

**Comment by lukehoban** [comment]
I don't see the same thing shown in the first screenshot myself - but I do see a slightly more minor issue that the page now has a horizontal scroll on mobile, seemingly because the download button overflows the viewport. Will the change here also address that?

image

image

**Comment by susanev** [comment]
@lukehoban can you try the latest preview?

**Comment by lukehoban** [comment]
> @lukehoban can you try the latest preview?

Yep. That looks great for me on mobile. No horizontal scroll.

**Review by zchase — APPROVED** [review]
THANK YOU!!!

**Pull request merged**
