### PR TITLE
add info on how to add urself to the website

### PR DESCRIPTION
**Pull request by susanev**
i know this is in onboarding docs in a few different places, but it seemed most relevant to have this content available in the repo where you add it. @cnunciato any thoughts on this?

### CODE REVIEW

**Comment by cnunciato** [comment]
@susanev could you point me to the places where these instructions already exist? I don't think I've seen them, so would be good to know where they are and what's in them.)

**Comment by susanev** [comment]
@cnunciato its part of the instructions that Casie sends to folks that ive never actually seen i don't think, and its also part of the engineering checklist that some managers use for onboarding https://github.com/pulumi/home/issues/new?template=5-onboarding-checklist.md&title=Onboarding+Checklist%3A+%5Bdescription%5D

**Comment by cnunciato** [comment]
Sorry for the delayed response on this. Chatted with Casie, and I agree it'd be good to have these docs close to the repo, but I'm thinking we should maybe start pulling this stuff into the repo wiki so it's a bit more navigable, easily consumable, updatable, etc. What would you think of that?

**Comment by susanev** [comment]
@cnunciato i didnt see anything in the wiki for this repo. i know there's been back and forth in the eng org about when we should use wikis and when we should use markdown. i kinda would like to just get this in, and then maybe we should reach out to folks and make sure folks are mostly good with using the wiki for this stuff.

**Comment by mattstratton** [comment]
Whenever these instructions that get into the onboarding and stuff happen, I would also recommend that there is some kind of option that is "if you don't have pulumi-hugo setup and don't want to, you can ask in x channel for someone to do it for you if you ask nicely" or something. setting up an entire environment for hugo, etc, when the only time someone will use it is for that one single PR seems like something that can be done elsewhere? or maybe casie already handles it?

**Comment by susanev** [comment]
@mattstratton sure! these were grabbed directly from the instructions today but im totally down to update them.

@cnunciato do you feel strongly that this needs to be in the repo wiki?

**Comment by mattstratton** [comment]
I'm actually curious what folks who don't use this repo do today - i'm gonna go out on an limb and say there's a nonzero number of employees who had it done for them, I wonder how they knew who to ask? :)

**Comment by susanev** [comment]
Freddy used to open issues to add new folks, and then I believe Christian and Zack would open prs for those issues. I think that practice stopped, not totally sure what the process is now, Christian do you?

**Comment by susanev** [comment]
@cnunciato would you prefer if i close this?

**Pull request closed without merging**
