### PR TITLE
Updated docs landing page

### PR DESCRIPTION
**Pull request by kimberleyamackenzie**
This PR updates the docs landing page 🎉 

Right now this PR is using my theme PR for that module, that will need updating after approval and pre-merge.

Ticket: https://github.com/pulumi/pulumi-hugo/issues/1169
Designs: https://www.figma.com/file/eSe3rvnOP2kVHgIZhZrlKq/docs-landing?node-id=359%3A21
Theme PR w/ styles + js: https://github.com/pulumi/theme/pull/91

### CODE REVIEW

**Comment by susanev** [comment]
@kimberleyamackenzie a few things...
- the overview pages which are the pages you get to when you interact with the headings in the left nav, lets just remove this entirely from this page
- can we reduce the font-size of the registry call out so it fits entirely on one line, at least for the max-width
- seeing it live now, id like to move converters to be between intro and reference (this may mean @jonelleb would like you to change up which cards get the circles)

**Comment by susanev** [comment]
the heading link icon also doesnt have enough space, we should give it a bit more so its not almost on top of the get started button
heading-link

**Comment by jonelleb** [comment]
@susanev + @kimberleyamackenzie, if we're moving Converters between Intro and Reference, here's a new screenshot with the new position of cards and the circles in the cards changed up a bit:

Screen Shot 2022-03-25 at 9 03 15 AM
.

**Review by jonelleb — CHANGES_REQUESTED** [review]
Looks great to me. There were a couple of changes Susan mentioned about card positions switching up so I've attached a new screenshot for that in the issue. If Susan is okay with that screenshot I think once that change is made we're good. Thanks!

**Comment by kimberleyamackenzie** [comment]
Latest revision should have addressed all the feedback above - some screenshots below!

Screen Shot 2022-03-25 at 2 03 03 PM
Screen Shot 2022-03-25 at 2 03 30 PM
Screen Shot 2022-03-25 at 2 04 21 PM

**Review by susanev — APPROVED** [review]

**Comment by cnunciato** [comment]
Yay! I'd like to review this before merging, but would rather not do so over the weekend. Will do first thing Monday, though!

**Review by jonelleb — APPROVED** [review]
Looks great! Thanks for the fast work!

**Review by zchase — APPROVED** [review]
Nice! Looks great!

**Comment by kimberleyamackenzie** [comment]
Closing this PR out, the UX team is going to re-approach this work at a future time.

**Pull request closed without merging**
