### PR TITLE
update styles for breadcrumbs

### PR DESCRIPTION
**Pull request by susanev**
## Description
fixes https://github.com/pulumi/docs/issues/8978
some open questions for @anita-trimbur in figma
and i need to figure out why registry breadcrumbs are not cooperating, oh its prolly cause i changed the class name, heavy sigh
registry pr: https://github.com/pulumi/registry/pull/2482

for space above and below; ill tackle that in the page layout changes

should not merge until after the docs nav changes land
Screenshot 2023-05-14 at 7 49 30 PM
Screenshot 2023-05-14 at 7 49 21 PM
Screenshot 2023-05-14 at 7 49 08 PM
Screenshot 2023-05-14 at 7 47 48 PM
Screenshot 2023-05-14 at 8 09 52 PM

## Checklist:

- [x] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [x] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [x] I have manually confirmed that all new links work.
- [x] I added aliases (i.e., redirects) for all filename changes.
- [x] If making css changes, I rebuilt the bundle.

### CODE REVIEW

**Comment by anita-trimbur** [comment]
from figma
- [ ] re: the "<>" affordance; the breadcrumbs are the one place where it's kinda weird that we don't have a parent page for all documentation. i likethat we could have an affordance that all the docs belonged to this parent concept, but i also thought it would be weird in the case of <> / Docs that both the "<>" and the "Docs" would go to the same place? i would support either adding the link or removing it entirely. one benefit of removing is that it makes more sense that this component is reused in learn rn.
- [ ] [standard hover styles](https://www.figma.com/file/CPxzPFMWrtbZOjZXy88418/pulumi-docs?type=design&node-id=590%3A9425&t=YsZETsggvCb4OEj4-1) apply (roomier underline in gray600)

**Comment by susanev** [comment]
@anita-trimbur id prefer to stick with Docs and Registry for now, but we can revisit the breadcrumbs in the future; that sound okay?

**Comment by susanev** [comment]
@anita-trimbur special cased the distance between the hover line on this one since the text is so small, let me know what you think

**Review by sean1588 — COMMENTED** [review]
code lgtm!

**Pull request merged**
