### PR TITLE
update kubecon page for NA kubecon

### PR DESCRIPTION
**Pull request by shughes26**
## Description
KubeCon page updated per [figma](https://www.figma.com/file/vFCIYm2xkWUPMMfr1PTfrX/Event-Pages-(InPerson%2Fbooth)?type=design&node-id=509-573&mode=design&t=HMxt5Ma64CNRI7Tb-0)

omitted customers and testimonials for now

## Checklist:

- [x] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [x] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [x] I have manually confirmed that all new links work.
- [x] I added aliases (i.e., redirects) for all filename changes.
- [x] If making css changes, I rebuilt the bundle.

### CODE REVIEW

**Review by sean1588 — APPROVED** [review]
lgtm!

**Comment by SaraDPH** [comment]
@shughes26 is there a reason why the Request a Demo was not included? Also, the banner doesn't extend to the length of the page as the previous one did, is it a dimension issue? If so do you know what was the dimension of the image before?

**Comment by shughes26** [comment]
@SaraDPH having a banner image stretches the full width without distortion (and stays responsive with the page) doesn't work well. I followed the pattern we used for PulumiUP for handling the hero image

I wasn't sure what to do with "request a demo" since the text and CTA in Figma are about workshops. Can you update the figma to reflect what that card should say?

**Comment by SaraDPH** [comment]
@shughes26  Ugh, where did the copy go?! I re-added it... sort of. I don't actually remember what I had thought of before. Hah.

**Review by SaraDPH — APPROVED** [review]

**Comment by SaraDPH** [comment]
@shughes26 Squash it! :)

**Pull request merged**
