### PR TITLE
Layout updates to /terraform

### PR DESCRIPTION
**Pull request by cnunciato**
Not yet ready for feedback. 😉 

Fixes https://github.com/pulumi/devrel-team/issues/453.

### CODE REVIEW

**Comment by aaronkao** [comment]
Looking good

- I would flip Pulumi TypScript with the HCL code. It being shorter on the left automatically attracts attention. 
- Between Scalability and Productivity, I would change the background color a bit
- The code under Classes seems to be the loop code correct?

**Comment by aaronkao** [comment]
fixes pulumi/devrel-team/issues/145

**Comment by susanev** [comment]
@cnunciato @aaronkao is this something yall are still hoping to get in?

**Comment by cnunciato** [comment]
@susanev Yes, we are still working on it.

**Comment by susanev** [comment]
@cnunciato hate to be a jerk, but could we close this until you are working on it again? happy to keep your branch around. we tracking open prs in engineering and im trying to keep on top of them.

**Comment by cnunciato** [comment]
@susanev Appreciate you keeping on top of things. We do still want to complete this WIP, but if the PR is bothersome, I'll close for now (but please do leave the branch).

**Pull request closed without merging**
