### PR TITLE
Corrected incorrect statement about Python popularity

### PR DESCRIPTION
**Pull request by karolzlot**
https://insights.stackoverflow.com/survey/2020#technology-most-loved-dreaded-and-wanted-languages-loved
"% of developers who are developing with the language or technology and have expressed interest in continuing to develop with it"

Possibly some other statistic may better fit this article.

### CODE REVIEW

**Comment by karolzlot** [comment]
btw 2021 data is available

**Comment by iwahbe** [comment]
You're right. Can you update the data and link to the [new survey](https://insights.stackoverflow.com/survey/2021#section-most-loved-dreaded-and-wanted-programming-scripting-and-markup-languages) while you're at it?

**Comment by karolzlot** [comment]
No, I won't do it.

**Comment by iwahbe** [comment]
No problem. Thanks for pointing it out to us!

**Review by iwahbe — APPROVED** [review]

**Pull request merged**
