### PR TITLE
Add a Deploy with Pulumi button option to template pages

### PR DESCRIPTION
**Pull request by cnunciato**
Fixes https://github.com/pulumi/devrel-team/issues/439.

### CODE REVIEW

**Comment by susanev** [comment]
@cnunciato i appreciate us adding the deploy with pulumi buttons, thank you!!

would you be at all willing to put this in the right-panel? or below the top-page heading, so its above the fold?

seems a bit weird to me that we are suggesting this as an option after they run the pulumi new command, am i missing something?

**Comment by cnunciato** [comment]
@susanev Totally open to any suggestions y'all have here, yep. I like the right-hand side thing for sure -- the only concern there would be making it clear this is kind of an either-or situation in that you either deploy with the CLI using "these commands here" _or_ with the Service using this button). Also relevant that the actual URL changes depending on the language selection, too, so that's a slight wrinkle to keep in mind as well. But yes -- any suggestions y'all have with those things in mind would be awesome and much appreciated!

**Comment by cnunciato** [comment]
> is it possible to send them to the new project landing page instead

Doesn't look like the console supports that as of now (or at least I'm not seeing any URL params change when I switch between the various options on that page).

**Comment by cnunciato** [comment]
To be honest, I'm very much on the fence about adding these buttons at this point, given the experience we have now, since you still end up returning to the CLI to run commands -- you just run slightly different commands. So it may actually make more sense to hold off and add them later -- but curious to hear others' thoughts on it.

**Comment by scottslowe** [comment]
I like the current placement. I think it makes sense to me, given the workflow involved and such, and the wording ("Alternatively, you can...") seems pretty natural. I'd vote for the current placement and treatment.

**Comment by aaronkao** [comment]
Good with the placement here. Ditto on Scott's comment on wording

**Review by scottslowe — APPROVED** [review]
LGTM

**Pull request merged**
