### PR TITLE
Fix highlighting of URN components

### PR DESCRIPTION
**Pull request by williamsbdev**

### CODE REVIEW

**Comment by susanev** [comment]
@williamsbdev can you help me understand this one? you prefer them to be left-aligned instead of centered? or something else?

**Comment by susanev** [comment]
@williamsbdev heres the before and after that im seeing...

## before
before

## after
after

@cnunciato do you have preferences on this?

**Comment by williamsbdev** [comment]
@susanev - Exactly! The after feels like the `^` characters are aligned now with the section of the URN that it's trying to define.

**Review by cnunciato — APPROVED** [review]
Looks good, thanks @williamsbdev!

**Pull request merged**
