### PR TITLE
adjust top nav to use a stronger font-weight instead of opacity on hover

### LINKED ISSUE #427: redesign marketing top-navigation menus
This is a super minor piece of feedback, however, I find it odd that we grey out the top nav links when you hover over them. Typically in most websites I use, the hover behavior is to make the target link look _more_ activated rather than _less_, and to me greying something out typically indicates it is unimportant, not clickable, etc.

For instance:

image

Notice when I hover over Cloud Engineering, I get:

image

I assume this was intentional (I see in the original website design it was present also), and perhaps I'm the only person with this reaction, however, it strikes me as odd every time I see it so I figured I would mention.

### PR DESCRIPTION
**Pull request by susanev**
## overview
moving from applying opacity to menu items on interaction to making them have a stronger weight for usability improvements.
fixes #427

### CODE REVIEW

**Comment by susanev** [comment]
@kimberleyamackenzie is gonna take over this work

**Review by zchase — COMMENTED** [review]
I think we are going to want to adjust the CSS so that the other menu items don't move when the bold text is applied. Thoughts @cnunciato ?

**Comment by kimberleyamackenzie** [comment]
@zchase Yeah, susan and I chatted about this yesterday and I'm going to adopt the PR + move to adjusting text shadow instead of font weight to avoid the shifting and make the transition a little less abrupt.  I have a few other things on my plate, but am aiming to get to this this afternoon.

**Comment by cnunciato** [comment]
Agree with this improvement for sure. We could also just darken the text color on hover.

**Comment by kimberleyamackenzie** [comment]
Adventures in CSS!  I pushed a change that uses the bold on hover strategy, but adds an invisible bold pseudo-element to ensure that the other elements don't experience that shifting.  I landed here after trying a few different things, all with some drawbacks - let me know what y'all think, or if you like one of the below better. @cnunciato @zchase 

Other ideas I tried:

Following your suggestion, @cnunciato, and doing black text on hover.  The contrast didn't feel enough to me:
Screen Shot 2021-08-11 at 11 13 49 AM

Using text shadow to emulate font weight - this one felt a little fuzzy to me around the edges because of the blur radius:
Screen Shot 2021-08-11 at 11 15 07 AM

Using text stroke - I liked this the best, but text stroke is technically non-standard:
Screen Shot 2021-08-11 at 11 14 45 AM

**Comment by cnunciato** [comment]
@kimberleyamackenzie Do you happen to have a commit you could push that shows the text-stroke approach? I see that it's technically non-standard, but it also looks pretty well supported. (The jump between normal and bold looks a bit abrupt to me, so would just like to see what the others look like in comparison.)

**Comment by kimberleyamackenzie** [comment]
@cnunciato Here's a gif demo, can definitely push a commit if you want to play around
Aug-11-2021 11-55-06

**Comment by cnunciato** [comment]
Yeah I definitely prefer that, too. I'd be 👍 on going that route for now, since it looks good, is currently well-supported, and is easily updated if support for text-shadow suddenly goes away.

NOW my question is ... is it `transition`able? 😇

**Comment by kimberleyamackenzie** [comment]
@cnunciato Pushed the version with the text stroke.  Weirdly (i guess this is where "non-standard" comes in), only the stroke color is `transition`able, not the stroke width - so adding the transition just looks kind of bizarre, in this case, in my opinion.

**Comment by susanev** [comment]
@cnunciato did you have more thoughts you wanted to share about this?

**Comment by cnunciato** [comment]
@susanev @kimberleyamackenzie and I did some back-and-forth on this after that last commit, and neither of us was able to come up with something that we felt quite worked, so we set it aside and haven't come back to it yet.

**Pull request closed without merging**
