### PR TITLE
Addshownotes page for dev advocates

### PR DESCRIPTION
**Pull request by zchase**

### CODE REVIEW

**Comment by susanev** [comment]
@zchase is this waiting on an action from someone else?

**Comment by zchase** [comment]
@susanev No, I will pick this work back up here soon. I'll make a decision whether to update this PR or just create a new one when I pick the work back up.

**Comment by susanev** [comment]
is this separate from https://github.com/pulumi/pulumi-hugo/pull/1281?

**Comment by cnunciato** [comment]
So @zchase it looks like we can want close this, as it looks like ~everything here was completed with #1281.

**Comment by susanev** [comment]
closing for now, will reopen if this work is revisited.

**Pull request closed without merging**
