### PR TITLE
removing confusing line about policy in aws get started guide

### PR DESCRIPTION
**Pull request by susanev**
fixes https://github.com/pulumi/pulumi-hugo/issues/1686

### CODE REVIEW

**Comment by cnunciato** [comment]
Do you think that if we delete this one, we should do the same for the other clouds as well? Both Azure and Google Cloud have similar guidance.

**Comment by susanev** [comment]
@cnunciato i looked at azure and google cloud, there language is different and not as confusing. do you feel strongly that they need to be removed?

**Review by lukehoban — APPROVED** [review]

**Comment by cnunciato** [comment]
> do you feel strongly that they need to be removed?

Not at all, just wanted to make sure we'd looked at 'em. 

Might be nice to have the AWS example align a bit better with the other two, which do seem clear:

Azure:

> In this guide, you will need a user account with permissions to create and populate Blob storage containers

GCP:

> In this guide, you will need an IAM user account with permissions that can create and populate a Cloud Storage bucket

Whereas with AWS:

>  Pulumi requires cloud credentials to manage and provision resources. You must use an IAM user account that has **Programmatic access** with rights to deploy and manage resources handled through Pulumi.

.. but that's not necessarily something we need to do for this PR.

**Comment by cnunciato** [comment]
> i don't think it makes sense to go further in depth to this in the guide

Nor do I -- I'll just submit a PR that shows what I mean.

**Pull request merged**
