### PR TITLE
Fix a typo in the typescript dynamic provider example

### PR DESCRIPTION
**Pull request by MitchellGerdisch**
## Checklist:

- [x ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [ ] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [ ] I have manually confirmed that all new links work.
- [ ] I added aliases (i.e., redirects) for all filename changes.
- [ ] If making css changes, I rebuilt the bundle.

### CODE REVIEW

**Comment by SpainTrain** [comment]
I think it needs to be instantiated like in  https://github.com/pulumi/pulumi-hugo/pull/3278/files (this is consistent with the Python examples too)

**Review by cnunciato — APPROVED** [review]
Thanks @MitchellGerdisch!

**Comment by cnunciato** [comment]
May have jumped the gun here, as I just noticed @SpainTrain's comment. I'll verify this locally and if necessary, revert.

**Comment by cnunciato** [comment]
Yeah, looks like this does need to be an instance of `pulumi.dynamc.ResourceProvider`. We have an example of this in the examples repo: https://github.com/pulumi/examples/blob/955617680f6224019b86f14c76f5a1f72ba1a917/aws-ts-eks-distro/eksdistro/index.ts#L105 I'll revert.

**Comment by cnunciato** [comment]
Oh no! I see you submitted the correction as well! I should've check for that first. 🤦 I'll see if I can get this fixed up.

**Pull request merged**
