### PR TITLE
update iac/aws workshop for february

### PR DESCRIPTION
**Pull request by shughes26**
https://github.com/pulumi/marketing/issues/678

### CODE REVIEW

**Comment by SaraDPH** [comment]
@prischoi, what time does it show to you? 

@shughes26 I see that the file says 9 AM PT, but it is not converting to the correct TZ to me. It should say 11 AM CST.
image

**Review by SaraDPH — APPROVED** [review]
I'm approving because the file is correct, although TZ conversion doesn't seem to be happening correctly.

**Comment by prischoi** [comment]
> @prischoi, what time does it show to you?
> 
> @shughes26 I see that the file says 9 AM PT, but it is not converting to the correct TZ to me. It should say 11 AM CST. image

I don't see this workshop at all on the Resources page? The only one I see is on 2/14.
Screenshot 2023-01-11 at 7 46 35 PM

**Comment by prischoi** [comment]
I'm getting 11 AM EST when pulling up the page which I assume is incorrect since it should be 12 since the correct time is 11 AM CST?

Screenshot 2023-01-12 at 9 45 46 AM

**Comment by SaraDPH** [comment]
Yep, I should be seeing 11 AM, and you would see 12 PM. @shughes26 do you know how to fix the TZ conversion?

**Comment by shughes26** [comment]
@prischoi @SaraDPH I'm looking into it

**Comment by shughes26** [comment]
@prischoi @SaraDPH https://github.com/pulumi/pulumi-hugo/pull/2398 turns out I'd used the wrong offset because of daylight savings

**Pull request merged**
