### PR TITLE
add slack logo for pkg

### PR DESCRIPTION
**Pull request by susanev**

### CODE REVIEW

**Comment by susanev** [comment]
@jkisk i think ur gonna need to update the package to use this method for the logo, but not totally sure; we want this way so we can remove the extra whitespace that slack adds to it by default

**Review by kimberleyamackenzie — APPROVED** [review]

**Comment by stack72** [comment]
@susanev how can we control this for 3rd party packages? We can't always download a copy of the logo right? Is there something we need to do that's better here?

**Comment by susanev** [comment]
@stack72 we can maybe find a tool that strips the whitespace from the logos, @kimberleyamackenzie do you know of anything that does that?

**Comment by kimberleyamackenzie** [comment]
not that i know of, but i'll bet there's something out there if i poke around a little bit more

**Review by jkisk — APPROVED** [review]
Thank you!

**Pull request merged**
