### PR TITLE
updating Azure classic 2.0 blog

### PR DESCRIPTION
**Pull request by meagancojocar**

### CODE REVIEW

**Review by susanev — COMMENTED** [review]
can you use relrefs pls?

**Comment by stack72** [comment]
@susanev it looks like the page doesn't use relref at all - maybe we just merge this to remove the broken links and then comb through the site to find non relref work?

**Review by stack72 — APPROVED** [review]
I am going to file an issue to comb through our site for non relref links but I'd love to push this in for now to remove that broken link

**Comment by susanev** [comment]
oh sure no worries. i had an issue for updating all the links but i cant find it, so thx for opening a new one. the problem with not using relrefs is that if anything changes in the future we wont know these links are broken, and the error messages wont give enough context to find them.

**Comment by stack72** [comment]
> oh sure no worries. i had an issue for updating all the links but i cant find it, so thx for opening a new one. the problem with not using relrefs is that if anything changes in the future we wont know these links are broken, and the error messages wont give enough context to find them.

You are 100% correct in us needing to fix them :) I will have a PR open soon:tm:

**Pull request merged**
