### PR TITLE
Update Pulumi Security page

### LINKED ISSUE #1346: Add Enterprise and Security pages to pulumi website footer
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Add links to the /enterprise/ and /security/ pages in the bottom footer of pulumi.com. Add "Enterprise" above "AWS". Add "Security" under "Public Roadmap".

### PR DESCRIPTION
**Pull request by gthuang**
Include content and link to the Security Whitepaper.

Fixes #1346.

### CODE REVIEW

**Comment by gthuang** [comment]
@cnunciato could you please help me upload the security whitepaper to our bucket so we can link to it from this page?

**Comment by cnunciato** [comment]
@gthuang You bet -- will sync up with you this morning on this and on #1346.

**Review by cnunciato — APPROVED** [review]
@gthuang I'm "approving" so you can merge when you like, but feel free to add any changes you want as suggestions and I'll get 'em added.

**Comment by gthuang** [comment]
@cnunciato could we get a more descriptive name for the whitepaper pdf?

**Comment by cnunciato** [comment]
@gthuang Ah, do you mean for the filename? Like maybe `pulumi-cloud-security-whitepaper.pdf`?

**Comment by gthuang** [comment]
@cnunciato Yes, I meant the filename. That suggestion looks good.

**Comment by cnunciato** [comment]
I'll go ahead and merge this, and we can make any adjustments we like as follow ups. 🚀

**Pull request merged**
