### PR TITLE
Fix layout shift on language change

### PR DESCRIPTION
**Pull request by cnunciato**
Fixes a slight layout shift that occurs when selecting the C# option, due to variable content width. Video shows the before and after:

https://user-images.githubusercontent.com/274700/189989424-a74f2b82-33ee-45e4-b7fc-6a4fa7ff98cd.mov

Also removes some superfluous classnames and fixes an off-center label on this template's meta image.

### CODE REVIEW

**Comment by susanev** [comment]
any chance this means you know the fix for this?
https://github.com/pulumi/pulumi-hugo/issues/72

**Review by nimbinatus — APPROVED** [review]
LGTM

**Review by scottslowe — APPROVED** [review]
LGTM

**Comment by cnunciato** [comment]
@susanev Perhaps -- do you have a link that repros this elsewhere? I clicked around a bit (as I seemed to remember something similar), but didn't immediately find one.

**Comment by susanev** [comment]
@cnunciato yah it repos on the page mentioned in the issue. i can zoom and show you sometime if you want.

**Pull request merged**
