### PR TITLE
Add ESC + Direnv guide

### PR DESCRIPTION
**Pull request by pgavlin**
Add a page that explains how to integrate ESC with Direnv.

### CODE REVIEW

**Comment by pgavlin** [comment]
I'm not entirely sure that this should be part of the getting started, but I didn't have a better idea of where to put it. Maybe we should have an "integrations" section?

**Comment by pgavlin** [comment]
(we should update https://github.com/direnv/direnv/wiki#tools-integration and add a link to this page once it is deployed)

**Comment by pgavlin** [comment]
Okay, this should be ready to go.

These changes now add a new section to the ESC menu, "Other Integrations", which links to the IaC guide and the new Direnv guide.

**Comment by pgavlin** [comment]
PTAL @arunkumar611

**Review by arunkumar611 — APPROVED** [review]
Looks good. 

We need to create additional content for Pulumi IaC page and add it there. Experience of clicking on it its pretty jarring.

**Pull request merged**
