### PR TITLE
Update docs header + search

### PR DESCRIPTION
**Pull request by kimberleyamackenzie**
This PR updates the docs header + search.  Specifically:
- Replace current nav with the practitioner nav, in docs only
- Other www surfaces (blog, marketing pages, registry) should not have their header behavior changed
- Move search to the top header in docs, removing it from the left-side navigation
- When scrolling, search should be sticky - remaining on the page as folks scroll
- When practitioner nav is out of view, a Pulumi logo appears next to the search box

Related changes in theme: https://github.com/pulumi/theme/pull/89
Ticket: https://github.com/pulumi/pulumi-hugo/issues/883

Screen Shot 2022-03-21 at 5 09 48 PM
Screen Shot 2022-03-21 at 5 09 55 PM

### Mobile
I took the logic we use in Registry, and removed the "search" button on screens below medium.

Screen Shot 2022-03-21 at 4 26 48 PM

### CODE REVIEW

**Review by susanev — APPROVED** [review]
wonderful thank you!!

a few things..

- lets align the search button background color to the rest of the primary buttons in docs; this is my fault, its off in the fima file.. im sorry!
- can we adjust the tertiary top nav both here and in registry so the content isn't constrainted to the fixed width and the logo and pages move to the left and right depending on screen size? i can open a new issue if you prefer

**Comment by kimberleyamackenzie** [comment]
Latest revision includes the updated button color + I updated the screenshots in the PR description to show as well.  @susanev and I slacked, and are gonna tackle the practitioner nav alignment in a separate issue.

**Comment by susanev** [comment]
we are going to hold this work until April 4th

**Review by zchase — APPROVED** [review]
LGTM! 

From what I can tell we are going to lose the marketing banner on all the docs pages once we merge this in. Any way we can do some follow-up work to get a banner back into the new nav? cc// @susanev

**Comment by susanev** [comment]
Yes absolutely! I think we already have an issue but if we don't ill get one opened.

**Review by susanev — APPROVED** [review]

**Pull request merged**
