### PR TITLE
Indicate there's more content in docs TOC

### PR DESCRIPTION
**Pull request by kimberleyamackenzie**
[There is an associated Theme PR for this work](https://github.com/pulumi/theme/pull/108/) - I have the `do not merge` label here to ensure this work is not merged until the theme PR is merged as well.

### Changes in this PR
- Add new anchor links section to the left docs nav to help make it clear that the nav has more content than what appears on screen
- Add new behavior so that when those anchor links are clicked, the nav scrolls that section into view in addition to navigating to the associated overview page
- Add overview pages for converters and support to create consistency in this behavior

#### New left nav anchor links
Screen Shot 2022-04-21 at 10 47 55 AM

#### Background animation when anchor links are scrolled to
Screen Shot 2022-04-21 at 10 48 12 AM

#### Gif of new scroll behavior with anchor links

https://user-images.githubusercontent.com/25756367/164520952-f2fb4039-3b61-48d2-a89e-5faa6fdf703c.mp4

#### New converters and support overview pages
Screen Shot 2022-04-21 at 10 48 46 AM
Screen Shot 2022-04-21 at 10 48 55 AM

### Links
Ticket: https://github.com/pulumi/pulumi-hugo/issues/1178
Designs: https://www.figma.com/file/8kz7uSX7MD430hCwl7q8Ll/Jonelle's-Work?node-id=23%3A768

### CODE REVIEW

**Comment by kimberleyamackenzie** [comment]
@jonelleb Let me know what you think of the behavior with the left nav scrolling after clicking the link on this, and if there's anything you'd like to be adjusted.  

Also, I implemented what we talked about for the `Support` header (linking to the first item in that nav, since it does not have an overview page) but I don't have a link here on the `Converters` header, because all the links under that heading navigate outside of docs.  Let me know what you think would be best here.

**Comment by jonelleb** [comment]
@kimberleyamackenzie + @susanev - is it possible for us to build a new page for Converters similar to the Reference page (http://pulumi-hugo-origin-pr-1378-5f4bd30a.s3-website.us-west-2.amazonaws.com/docs/reference) that would list the name of the Converters pages and give a brief description of them with links to each? Honestly I feel like this may be the only solution since each Converters links outside of docs and the user no longer has that left nav anymore.

**Comment by susanev** [comment]
would yall be up to zoom about this today?

**Comment by jonelleb** [comment]
Sure.

**Review by jonelleb — APPROVED** [review]
This looks great! I love the highlight! 👍  Thanks for all the extra effort you put in to make it just right.

**Review by zchase — APPROVED** [review]

**Pull request merged**
