### PR TITLE
add a docs footer and style it

### PR DESCRIPTION
**Pull request by susanev**
## Description

this is adding a new footer to docs pages
no changes to the marketing footer
[ux designs in figma](https://www.figma.com/file/CPxzPFMWrtbZOjZXy88418/pulumi-docs?type=design&node-id=674%3A15260&t=wzKEkdjmVij4MvhX-1)

we should not merge this until the docs nav changes land

fixes https://github.com/pulumi/docs/issues/8970

@anita-trimbur a few questions for you in figma; also i changed the border width from 3px to 2px cause it looked way too thick, but i can change it back if ya don't like it, let me know

it seems registry uses the marketing template not the docs template? or maybe its own template; so ill do that in a registry specific pr after this lands, if that's okay. let me know if you want them to ship together.

## Checklist:

- [x] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [x] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [ ] I have manually confirmed that all new links work.
- [x] I added aliases (i.e., redirects) for all filename changes.
- [x] If making css changes, I rebuilt the bundle.

### CODE REVIEW

**Comment by anita-trimbur** [comment]
from figma
- [ ] increase spacing between footer links (was previously 20) - is 24px enough of an increase? if not we can try 32px
- [ ] hover styles will be the [same as standard links](https://www.figma.com/file/CPxzPFMWrtbZOjZXy88418/pulumi-docs?type=design&node-id=590%3A9425&t=YsZETsggvCb4OEj4-1) (roomier underline in gray600)
- [ ] code styles added to figma frame
- [ ] 16px spacing between paragraphs
- [ ] top and bottom margin 16px
- [ ] should we consider orange link text inside the warning notes? if we were to do that, we would need to use orange900 to meet contrast minimums

**Comment by susanev** [comment]
@anita-trimbur some of ur checklist items in here seem unrelated to the footer? unless im missing something

**Comment by anita-trimbur** [comment]
noticed that the spacing seems to be off at smaller sizes. seems like the container for the links should have more width than it does and that something is happening with the text alignment as well.
Screen Shot 2023-05-18 at 12 50 49 PM

**Comment by susanev** [comment]
@anita-trimbur this is fixed now

**Comment by anita-trimbur** [comment]
thanks, that was fast!! i'll approve now, but the final link is aligning weird at my smallest possible window size:

Screen Shot 2023-05-18 at 1 19 18 PM

**Review by anita-trimbur — APPROVED** [review]

**Review by sean1588 — APPROVED** [review]
this looks great! i love the new footer!

**Review by sean1588 — APPROVED** [review]
this looks great! i love the new footer!

**Pull request merged**
