### PR TITLE
new code font!

### PR DESCRIPTION
**Pull request by susanev**
## Description
@anita-trimbur take a look at the preview and let me know what you think
also happy to try other versions of this font, or any of the other fonts

fixes https://github.com/pulumi/pulumi-hugo/issues/2960

## Checklist:

- [x] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [x] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [x] I have manually confirmed that all new links work.
- [x] I added aliases (i.e., redirects) for all filename changes.
- [ ] If making css changes, I rebuilt the bundle.

### CODE REVIEW

**Comment by anita-trimbur** [comment]
i really like it! what do you think? do you like the slab, or would you want to see it without?

**Comment by susanev** [comment]
@anita-trimbur cool, lets ship it!

**Comment by lukehoban** [comment]
The code font chosen here uses ligatures. I’m fairly strongly against that by default. For reasons similar to those articulated here: https://practicaltypography.com/ligatures-in-programming-fonts-hell-no.html.

**Comment by anita-trimbur** [comment]
we can change from the term variant to the fixed variant to omit ligatures

**Comment by susanev** [comment]
lol down with ligatures, yah ill remove them later today.

**Comment by susanev** [comment]
@anita-trimbur this is updated, take another look, let me know what you think

**Review by anita-trimbur — APPROVED** [review]
still really like this! but am totally willing to defer if sean thinks otherwise. i've actually been mistakenly using iosevka sans the slab in figma, and i think that's a fine alternative if anyone is more inclined.

**Comment by sean1588** [comment]
I am fairly neutral on this font change as this is quite a subjective area when it comes to the aesthetics of things. 

I think aesthetically it looks nice, however I do think something feels a bit off about it though if I am being completely honest, but not sure what it is. I think it may be because I am not used to reading code in this font since it is not a font I am used to seeing in either my terminal or my code editor so that may be why it has a bit of an awkward feel me. I could be an anomaly though and maybe I just need to get used to seeing it so I'm willing to defer to what you all think.

**Comment by susanev** [comment]
@sean1588 @anita-trimbur kk let me try dropping the slab

**Pull request merged**
