### PR TITLE
Add note wrt opening ESC secrets

### PR DESCRIPTION
**Pull request by desteves**
Adds an info note to clarify that esc open is the correct command when opening a secret.

### CODE REVIEW

**Comment by desteves** [comment]
@arunkumar611 let me know if this'll work for https://github.com/pulumi/pulumi-hugo/issues/3727

**Comment by arunkumar611** [comment]
We are working on a new doc update that might help with this issue. I'm not sure if this change alone will explain away the ambiguity on get vs. open. 

Instead of the new note - maybe we could modify the existing one 

from: 

Note that esc env get returns only statically defined plain-text values and definitions; it does not resolve provider-managed values or secrets. (For these, get returns the item definition with a value of [unknown].) To resolve dynamically retrieved values or secrets, you must instead [open the environment](http://localhost:1313/docs/pulumi-cloud/esc/environments/#opening-an-environment).

to 

Note that esc env returns only statically defined plain-text values and definitions; It does not return secrets defined in the environment or resolve values from specified provider configurations. (For these, get returns the item definition with a value of [unknown].) To resolve dynamically retrieved values or secrets, you must instead [open the environment](http://localhost:1313/docs/pulumi-cloud/esc/environments/#opening-an-environment).

**Comment by desteves** [comment]
@arunkumar611 Please take a look at the new changes based on the feedback provided :)

**Comment by desteves** [comment]
@arunkumar611, any thoughts on merging these changes?

**Review by arunkumar611 — APPROVED** [review]
LGTM

**Pull request merged**
