### PR TITLE
add CNCF on-demand workshop to resources list

### PR DESCRIPTION
**Pull request by shughes26**
## Description
https://github.com/pulumi/marketing/issues/788

## Checklist:

- [x] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [x] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [x] I have manually confirmed that all new links work.
- [x] I added aliases (i.e., redirects) for all filename changes.
- [x] If making css changes, I rebuilt the bundle.

### CODE REVIEW

**Comment by gthuang** [comment]
@shughes26 is it possible to still have registration landing page but just have it provide a CTA to visit the external workshop link? my reasoning is that it would be nice to have a pulumi landing page that we can still drive traffic to. @isaac-pulumi what do you think?

**Review by sean1588 — APPROVED** [review]

**Comment by SaraDPH** [comment]
@shughes26 I don't see the page live on Resources

**Comment by shughes26** [comment]
@SaraDPH it's there, title is "Build a self-service infrastructure platform on kubernetes"

**Comment by SaraDPH** [comment]
> @SaraDPH it's there, title is "Build a self-service infrastructure platform on kubernetes"

Thanks, I see it now :)

**Pull request merged**
