### PR TITLE
[Blog] Top 5 Things an Azure Developer Needs to Know: Introduction

### PR DESCRIPTION
**Pull request by spara**
This was supposed to be published last week but was delayed to this week. It was already approved.

### CODE REVIEW

**Review by praneetloke — APPROVED** [review]

**Comment by joeduffy** [comment]
@spara Is there a word missing from the title?

> Top 5 an Azure Developer Needs to Know: Introduction

Maybe is was meant to be

> Top 5 Things an Azure Developer Needs to Know: Introduction

?

**Comment by spara** [comment]
> @spara Is there a word missing from the title?
> 
> > Top 5 an Azure Developer Needs to Know: Introduction
> 
> Maybe is was meant to be
> 
> > Top 5 Things an Azure Developer Needs to Know: Introduction
> 
> ?

We have a 60 character limit for titles, if I add 'Things' then the other titles in the series would exceed 60 chars. I can fix it, but the titles will have to be reworked for the other articles and not consistent.

**Comment by joeduffy** [comment]
FWIW, I believe there's a meta-tag you can add to suppress the 60 character warning. I know that's bad SEO practice, but if you're asking me, I honestly prefer correct grammar in the titles than slightly exceeding the limit. Just my $0.02.

**Comment by spara** [comment]
I'll search for the metatag and fix it

**Comment by spara** [comment]
I dug through hugo and it looks like the check for title length happens
when the site is built from a PR. I'll dig through the build process
tomorrow.

I've fixed the title, if you approve this PR, I can merge it.

https://github.com/pulumi/pulumi-hugo/pull/475

**Pull request merged**
