### PR TITLE
Add templates as options on getting started landing page

### PR DESCRIPTION
**Pull request by zchase**
This PR adds the newly shipped templates as options in the Getting Started Guide. The main goal here is increase awareness and usage of the templates, and by offering them as options on the getting started page we should get more visibility.

**Hypothesis**

By presenting users more use case specific options in the getting started guide we will increase the CTR of users to these templates/guides and in turn increase the conversion rate of the website resulting in new users.

getting-started-options-tempaltes

### CODE REVIEW

**Comment by susanev** [comment]
@zchase can you sync up with @anita-trimbur we are calling the current one "Starter" in the service UI instead of "Simple". I think it would be good to align these things. Can y'all decide together on a direction?

**Comment by zchase** [comment]
@susanev I'll change it to "Starter" to align with y'all, "Simple" was just what I picked in the moment. Thanks for letting me know!

**Comment by aaronkao** [comment]
I think we should wait to roll this out until after some of this is addressed https://github.com/pulumi/devrel-team/issues/425. My original thinking was that Getting Started eventually would just use one of the template as part of its own flow. This level of choice I think might be more confusing. 

The short term change we could make is adding this on the Next Steps page - https://www.pulumi.com/docs/get-started/aws/next-steps/

**Comment by aaronkao** [comment]
Discussed in MBR on 10/18/2022. Good to ship and test. Tracking metrics https://docs.google.com/spreadsheets/d/1Z-xuAlLlRPvG6ksL8jcHVAHHjD1Y_SZAROYrptZyRcA/edit

**Review by sean1588 — APPROVED** [review]
Just one comment about the starter app. Other than that lgtm.

**Comment by sean1588** [comment]
> I do think it might be worth considering removing the links to pulumi/examples for now (since that experience is so much less guided than /templates), but I'll leave that to you.

plus one on that

**Pull request merged**
