### PR TITLE
Add slides to Matty's devopsdays Denver talk

### PR DESCRIPTION
**Pull request by mattstratton**

### CODE REVIEW

**Comment by susanev** [comment]
@mattstratton i think this is setup to only include slides once the event has past; though i think we can update this to allow a slides column in upcoming as well if yall need that

**Comment by mattstratton** [comment]
Yeah it’s weird - my talk is tomorrow morning and I want to tell people to go to Pulumi dot com slash matty for the slides :/

**Comment by mattstratton** [comment]
I think overall we need to revisit the ux  for people finding the slides as a call to action right after a talk is given

like, I want this uri on my final slide, etc instead of sending them to speaking.mattstratton.com for the slides

**Comment by susanev** [comment]
@mattstratton I think I can fix the slides thing now for you, mind if I push a commit later today?

**Comment by mattstratton** [comment]
I'll be around! I've got my phone and I appreciate it - I'm sorry this didn't occur to me until tonight (I'm the keynote tomorrow morning and this is all new to us to be doing it this way again ... in person and slides on projectors and stuff!)

**Comment by susanev** [comment]
cc/ @anita-trimbur @kimberleyamackenzie i adjusted this to allow slides for upcoming talks; we can revisit later if needed, was only trying to fix this quickly for matty

**Comment by susanev** [comment]
@mattstratton i do not know what is up with that failure but its happening on other prs too, so i moved this over to https://github.com/pulumi/pulumi-hugo/pull/1413 feel free to approve and merge whenever you want

**Pull request closed without merging**
